name: note_app
description: A new Flutter project.
version: 1.0.0+1

environment:
    sdk: ">=3.0.5 <4.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    flutter_markdown: ^0.6.17
    bitsdojo_window: ^0.1.5
    provider: ^6.0.5
    markdown_widget: ^2.2.0
    google_fonts: ^5.1.0
    flutter_highlight: ^0.7.0
    ionicons: ^0.2.2
    firebase_core: ^2.15.0
    firebase_auth: ^4.7.2
    cloud_firestore: ^4.8.4
    firebase_analytics: ^10.4.4
    firedart: ^0.9.7
    websafe_svg: ^3.0.1+1
    flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true

    # Add assets path
    assets:
        - assets/images/
        - assets/Icons/
